'use client';
import { useState } from 'react';
import { ArrowUpRight, ChevronRight, Command, Radio, GitBranch, Layers, Search, Pause, Play, Check, Clock3, ArrowDownRight } from 'lucide-react';
import { BrandLogo } from './brand-logo';
import './hero-command-center.css';

const decisions = [
  {id:'D–024',title:'Bring enterprise reporting forward',area:'Product strategy',owner:'AL',name:'Alex Lee',due:'Today',signal:'Enterprise buyers need clearer performance visibility.',source:'Customer research',time:'18 min ago',impact:'Expansion revenue',brief:'Three enterprise accounts raised the same gap. Bring reporting into the next planning cycle before committing more capacity to acquisition.',next:'Scope a focused reporting release with Product.',evidence:'3 customer conversations',risk:'Capacity moves away from the acquisition roadmap.'},
  {id:'D–023',title:'Validate the partner expansion opportunity',area:'Growth',owner:'MK',name:'Maya Kim',due:'Tomorrow',signal:'A distribution partner is opening a new enterprise channel.',source:'Partner update',time:'42 min ago',impact:'Distribution reach',brief:'The opportunity fits the enterprise focus. Validate demand and support requirements before making a launch commitment.',next:'Review the partner proposal with the growth lead.',evidence:'Partner proposal · channel review',risk:'Support demand may outpace the initial revenue.'},
  {id:'D–022',title:'Review the annual vendor commitment',area:'Operations',owner:'JS',name:'Jamie Shaw',due:'Fri, 11 Sep',signal:'The infrastructure renewal window opens next week.',source:'Internal operations',time:'1 hr ago',impact:'Operating margin',brief:'Renewal terms are approaching while usage is shifting. Compare the commitment against the latest capacity forecast.',next:'Reconcile usage and renewal terms with Finance.',evidence:'Usage forecast · renewal terms',risk:'A longer commitment reduces flexibility.'},
];
const series = { '7D':[5.1,4.8,4.9,4.1,4.3,3.6,3.1], '30D':[6.4,6.1,5.5,5.8,4.8,4.4,4.9,3.8,4.1,3.6,3.4,3.1] };
export function HeroCommandCenter(){
  const [selected,setSelected]=useState(0);
  const [mobilePanel,setMobilePanel]=useState<'priorities'|'velocity'|'context'>('priorities');
  const [view,setView]=useState<'Overview'|'Decisions'|'Signals'>('Overview');
  const [period,setPeriod]=useState<'7D'|'30D'>('7D');
  const [monitoring,setMonitoring]=useState(true);
  const [query,setQuery]=useState('');
  const [expanded,setExpanded]=useState(false);
  const item=decisions[selected];
  const values=series[period];
  const points=values.map((v,i)=>`${30+i*470/(values.length-1)},${130-(v-2)*23}`).join(' ');
  return <div className="hc-window" aria-label="Interactive Vantage Command Center preview">
    <aside className="hc-sidebar">
      <div className="hc-brand"><BrandLogo/><span>Vantage</span><span className="hc-workspace-mark">⌄</span></div>
      <div className="hc-workspace"><span className="hc-avatar">N</span><span>Northstar<span>Example workspace</span></span></div>
      <span className="hc-nav-label">WORKSPACE</span>
      <nav aria-label="Dashboard preview">{([['Overview',Command],['Decisions',GitBranch],['Signals',Radio]] as const).map(([label,Icon])=><button key={label} aria-pressed={view===label} onClick={()=>{setView(label);setMobilePanel('priorities')}}><Icon size={15}/><span>{label==='Overview'?'Command Center':label}</span>{label==='Decisions'&&<small>3</small>}</button>)}</nav>
      <div className="hc-focus"><span className="hc-nav-label">OPERATING FOCUS</span><div><Layers size={14}/> Enterprise growth</div><p>Context connected to every decision.</p></div>
      <div className="hc-side-bottom"><span className="hc-status-dot"/> Workspace connected<small>Last synced just now</small></div>
    </aside>
    <div className="hc-app">
      <header className="hc-toolbar"><div><Command size={14}/><span>Workspace</span><ChevronRight size={12}/><strong>{view==='Overview'?'Command Center':view}</strong></div><button className="hc-monitor" aria-pressed={monitoring} onClick={()=>setMonitoring(!monitoring)}><span className={monitoring?'hc-status-dot':'hc-paused-dot'}/>{monitoring?'Monitoring live':'Monitoring paused'}{monitoring?<Pause size={11}/>:<Play size={11}/>}</button></header>
      <div className="hc-body">
        <div className="hc-heading"><div><span className="hc-overline">YOUR BUSINESS, IN FOCUS</span><h2>{view==='Overview'?'Here’s what matters now.':view==='Signals'?'The change behind the decision.':'The calls that move you forward.'}</h2><p>Three priorities. The context to make the call.</p></div><span className="hc-date">06 Sep 2026</span></div>
        <div className="hc-metrics"><div><span>Priority decisions</span><strong>03 <small>Ready to review</small></strong></div><div><span>Incoming signals</span><strong>03 <small>Context linked</small></strong></div><div><span>Decision velocity</span><strong>3.1<span className="hc-unit">days</span><small><ArrowDownRight size={12}/> 2.0d this week</small></strong></div></div>
        <div className="hc-mobile-panels" aria-label="Dashboard panels">{(['priorities','velocity','context'] as const).map(panel=><button key={panel} aria-pressed={mobilePanel===panel} onClick={()=>setMobilePanel(panel)}>{panel==='priorities'?'Priorities':panel==='velocity'?'Velocity':'Live context'}</button>)}</div><div className="hc-grid" data-mobile-panel={mobilePanel}><div className="hc-main-column">
          <section className="hc-panel hc-decisions"><div className="hc-panel-title"><h3>{view==='Signals'?'Incoming intelligence':'Priority decisions'}</h3><span className="hc-count">03</span><span className="hc-panel-note">{view==='Signals'?'Newest first':'Needs your attention'}</span></div>
          {view!=='Overview'&&<label className="hc-search"><Search size={13}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={view==='Signals'?'Search signals…':'Search decisions…'} aria-label={`Search ${view.toLowerCase()}`}/></label>}
          <div className="hc-column-head"><span>{view==='Signals'?'SIGNAL / SOURCE':'DECISION / FOCUS'}</span><span>{view==='Signals'?'RECEIVED':'OWNER / DUE'}</span></div>
          {decisions.map((d,i)=>({d,i})).filter(({d})=>view==='Overview'||`${d.title} ${d.signal} ${d.source}`.toLowerCase().includes(query.toLowerCase())).map(({d,i})=><button className={`hc-decision-row ${selected===i?'is-selected':''}`} key={d.id} aria-pressed={selected===i} onClick={()=>{setSelected(i);setExpanded(false);setMobilePanel('context')}}><span className="hc-row-icon">{view==='Signals'?<Radio size={14}/>:<GitBranch size={14}/>}</span><span className="hc-row-copy"><strong>{view==='Signals'?d.signal:d.title}</strong><small>{view==='Signals'?d.source:`${d.id} · ${d.area}`}</small></span><span className="hc-row-meta">{view!=='Signals'&&<span className="hc-avatar">{d.owner}</span>}<small>{view==='Signals'?d.time:d.due}</small></span><ChevronRight size={13}/></button>)}
          {view!=='Overview'&&!decisions.some(d=>`${d.title} ${d.signal} ${d.source}`.toLowerCase().includes(query.toLowerCase()))&&<p className="hc-empty">No matches. Try another search.</p>}
          <div className="hc-list-footer"><span><Check size={12}/> Every priority has an owner</span><span>3 open</span></div></section>
          <section className="hc-panel hc-chart"><div className="hc-panel-title"><h3>Decision velocity</h3><span className="hc-panel-note">Signal → decision</span><div className="hc-period">{(['7D','30D'] as const).map(p=><button aria-pressed={period===p} key={p} onClick={()=>setPeriod(p)}>{p}</button>)}</div></div><div className="hc-chart-value">3.1 <span>days to a clear call</span><small>↓ {(values[0]-3.1).toFixed(1)}d over {period==='7D'?'7':'30'} days</small></div><svg viewBox="0 0 540 164" role="img" aria-label={`Example decision time fell from ${values[0]} to 3.1 days over ${period==='7D'?'7':'30'} days`}><defs><linearGradient id="hc-chart-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ff321f" stopOpacity=".13"/><stop offset="100%" stopColor="#ff321f" stopOpacity="0"/></linearGradient></defs>{[38,84,130].map((y,i)=><g key={y}><path d={`M30 ${y}H500`} stroke="white" strokeOpacity=".08" strokeDasharray="2 5"/><text x="517" y={y+4}>{6-i*2}d</text></g>)}<polygon points={`30,140 ${points} 500,140`} fill="url(#hc-chart-fill)"/><polyline points={points} fill="none" stroke="#ff321f" strokeWidth="2" strokeLinejoin="round"/>{values.map((v,i)=><circle key={i} cx={30+i*470/(values.length-1)} cy={130-(v-2)*23} r={i===values.length-1?3.5:2} fill={i===values.length-1?'#ff321f':'#b7b9bd'}/>)}<text x="30" y="160">{period==='7D'?'31 AUG':'08 AUG'}</text><text x="450" y="160">06 SEP</text></svg></section>
        </div><aside className="hc-panel hc-context" aria-label="Selected decision context" aria-live="polite"><div className="hc-panel-title"><h3>Live context</h3><span className={monitoring?'hc-status-dot':'hc-paused-dot'}/></div><div className="hc-context-body"><span className="hc-tag">PRIORITY / {item.id}</span><h3>{item.title}</h3>{expanded&&<p>{item.brief}</p>}<div className="hc-evidence"><span className="hc-overline"><Radio size={12}/> LINKED SIGNAL</span><strong>{item.signal}</strong><small>{item.source} · {item.time}</small></div><dl><div><dt>Impact</dt><dd>{item.impact}</dd></div><div><dt>Owner</dt><dd><span className="hc-avatar">{item.owner}</span>{item.name}</dd></div><div><dt>Review by</dt><dd><Clock3 size={12}/>{item.due}</dd></div></dl><div className="hc-next"><span className="hc-overline">NEXT MOVE</span><p>{item.next}</p></div>{expanded&&<div className="hc-brief"><span className="hc-overline">TRADE-OFF TO WEIGH</span><p>{item.risk}</p><small>Evidence: {item.evidence}</small></div>}<button className="hc-review" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}>{expanded?'Close decision brief':'Review decision'}<ArrowUpRight size={14}/></button></div></aside></div>
        {view==='Overview'&&<div className="hc-signal-strip"><span><Radio size={13}/> LATEST SIGNAL</span><button onClick={()=>{setView('Signals');setSelected(0)}}>Enterprise buyers need clearer performance visibility.<ArrowUpRight size={13}/></button><small>18 min ago</small></div>}
      </div><footer className="hc-statusbar"><span><span className={monitoring?'hc-status-dot':'hc-paused-dot'}/>{monitoring?'All sources connected':'Monitoring paused in preview'}</span><span>Interactive preview · Example data</span></footer>
    </div>
  </div>;
}
