/*
 * Sample data for the landing page's AppPreview demo. NOT live data.
 *
 * Ported from the design package's components/redesign/data.ts. Renamed and
 * relocated so it cannot be confused with the real dashboard's Supabase-backed
 * data — the dashboard reads signals/decisions from the database, never here.
 */
export type Area='Command'|'Signals'|'Strategies'|'Decisions'|'Advisor'|'Profile'|'Settings';
export const areas:Area[]=['Command','Signals','Strategies','Decisions','Advisor','Profile','Settings'];
export const signals=[
{id:'SIG–041',title:'AI inference costs are moving down',category:'Cost Base',urgency:'Act this week',time:'18m',source:'Vendor pricing update',confidence:84,summary:'Lower context costs create room to improve the margin of recurring AI workflows.',impact:'Your support and research workflows reuse the same context. Revisit their cost model before increasing usage.',act:'Benchmark the two highest-volume workflows, then compare cost per completed task.',inaction:'Existing workflows keep running, but avoidable cost compounds as usage grows.',strategy:'Reduce the cost of recurring AI workflows'},
{id:'SIG–040',title:'Enterprise buyers want clearer proof of value',category:'Pricing',urgency:'Decide this month',time:'42m',source:'Customer research',confidence:78,summary:'Recent buyer conversations put measurable outcomes ahead of additional features.',impact:'Expansion depends on whether champions can explain the result internally. Reporting may deserve priority over acquisition features.',act:'Test an executive outcome brief in the next three buyer conversations.',inaction:'Longer sign-off cycles may continue even if the feature set expands.',strategy:'Make the enterprise outcome easier to prove'},
{id:'SIG–039',title:'Vendor review requirements are expanding',category:'Compliance',urgency:'Decide this month',time:'1h',source:'Security review notes',confidence:76,summary:'Procurement teams are asking for more detail about AI vendors and data handling.',impact:'A repeatable vendor overview could remove friction from enterprise security reviews.',act:'Document the current vendor stack and data boundaries before the next review.',inaction:'Each new deal requires another round of ad hoc evidence gathering.',strategy:'Prepare a reusable vendor transparency brief'},
{id:'SIG–038',title:'A partner is opening a new distribution channel',category:'Competition',urgency:'Watch',time:'2h',source:'Partner briefing',confidence:68,summary:'A partner is testing a channel that could reach a new segment of enterprise buyers.',impact:'The audience fits, but demand and support effort still need validation.',act:'Ask for a small pilot with explicit demand and support checkpoints.',inaction:'The opportunity stays unproven; avoid treating it as committed revenue.',strategy:'Validate the partner channel with a bounded pilot'},
{id:'SIG–037',title:'Infrastructure renewal terms are approaching',category:'Cost Base',urgency:'Watch',time:'3h',source:'Operations brief',confidence:91,summary:'The renewal window is a chance to align your commitment with actual usage.',impact:'A longer agreement may reduce cost but limit flexibility as the architecture changes.',act:'Reconcile usage, expected capacity and renewal terms with Finance.',inaction:'The current commitment may renew without a fresh capacity review.',strategy:'Match infrastructure commitment to expected usage'},
{id:'SIG–036',title:'Funding conversations are shifting toward efficiency',category:'Capital',urgency:'Watch',time:'4h',source:'Market research',confidence:65,summary:'Capital discussions increasingly focus on efficient growth and credible operating assumptions.',impact:'A clear unit-economics story matters more than a larger feature roadmap.',act:'Review the operating assumptions behind the next funding milestone.',inaction:'A weak efficiency narrative could obscure the progress already made.',strategy:'Make the efficiency case explicit'},
];
export type Decision={id:string;title:string;area:string;status:'Open'|'Decided'|'Archived';owner:string;due:string;confidence:string;rationale:string;description:string;known:string;unknown:string;signal:number;analyzed:boolean;outcome?:string};
export const initialDecisions:Decision[]=[
{id:'DEC–018',title:'Prioritize enterprise outcome reporting',area:'Product',status:'Open',owner:'Alex Morgan',due:'2026-09-11',confidence:'Genuinely torn',rationale:'The reporting gap appears in buyer conversations and could be delaying enterprise sign-off.',description:'Decide whether to bring a focused reporting workflow into the next delivery cycle.',known:'Three buyer conversations raised the same need.',unknown:'Whether a shared outcome brief is enough before building a full workflow.',signal:1,analyzed:true},
{id:'DEC–017',title:'Rework the pricing model for AI usage',area:'Revenue',status:'Open',owner:'Maya Chen',due:'2026-09-14',confidence:'Just exploring',rationale:'We need a pricing model that supports margin without making invoices unpredictable.',description:'Compare a flat increase with a base subscription and usage allowance.',known:'Usage varies substantially across customers.',unknown:'Willingness to pay across the different tiers.',signal:0,analyzed:true},
{id:'DEC–016',title:'Pilot the partner distribution channel',area:'Growth',status:'Open',owner:'Jamie Shaw',due:'2026-09-18',confidence:'Pretty sure',rationale:'The channel could reach qualified buyers without a large upfront commitment.',description:'Agree on a bounded partner pilot before committing to a broader launch.',known:'The partner reaches our intended customer segment.',unknown:'Conversion rate and support effort per account.',signal:3,analyzed:false},
{id:'DEC–015',title:'Prepare the vendor transparency brief',area:'Operations',status:'Decided',owner:'Alex Morgan',due:'2026-09-09',confidence:'Pretty sure',rationale:'Reuse the same evidence across security reviews.',description:'Create a maintained vendor and data-handling brief.',known:'The same questions recur across reviews.',unknown:'Which details need legal review.',signal:2,analyzed:true,outcome:'Proceed with a single maintained brief; review at the next vendor change.'},
];
export const initialStrategies=signals.map((s,i)=>({id:`STR–0${21-i}`,title:s.strategy,signal:i,status:(i===2?'Decided':i===3?'Deciding':'Considering') as string}));
export const risks=[{title:'Strength of demand',severity:'High',text:'A repeated request is a useful signal, but it may not represent the wider customer base. Validate it across segments before committing.'},{title:'Opportunity cost',severity:'High',text:'Bringing this work forward displaces another priority. Name the work that moves back and its consequence.'},{title:'Success threshold',severity:'Medium',text:'Agree on the evidence that would justify a larger commitment before the first pilot begins.'}];
